# Generated by Django 5.0.6 on 2024-05-27 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=45)),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('engine', models.CharField(max_length=25)),
                ('transmission', models.CharField(max_length=25)),
                ('vin', models.CharField(max_length=17)),
                ('price_usd', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1500)])),
                ('slug', models.SlugField()),
            ],
        ),
    ]
