# Generated by Django 5.0.6 on 2024-05-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='about_car',
            field=models.TextField(default=''),
        ),
    ]
