# Generated by Django 5.0.6 on 2024-05-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0003_car_status_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(default='', upload_to='cars'),
        ),
    ]
