# Generated by Django 5.0.6 on 2024-05-31 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0004_car_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('surname', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('feedback', models.TextField(validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=60)),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
    ]
