# Generated by Django 5.0.6 on 2024-06-02 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0006_userclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
