# Generated by Django 5.0.6 on 2024-06-02 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0008_remove_userclient_codphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='codphone',
            field=models.CharField(choices=[('+375', '+375'), ('80', '80')], default='+375', max_length=4),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
